services:
  # Backend services
  web:
    image: nginx:latest
    volumes:
      - ./back:/var/www
      - ./back/docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - bukal-development
    depends_on:
      php-fpm:
        condition: service_started

  php-fpm:
    build:
      context: ./back
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    env_file:
      - ./back/.env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./back:/var/www
    networks:
      - bukal-development
    depends_on:
      postgres:
        condition: service_started

  workspace:
    build:
      context: ./back
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    ports:
      - '${VITE_PORT:-5173}:5173'
    tty: true
    stdin_open: true
    env_file:
      - ./back/.env
    volumes:
      - ./back:/var/www
    networks:
      - bukal-development

  postgres:
    image: postgres:16
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data-development:/var/lib/postgresql/data
    networks:
      - bukal-development

  redis:
    image: redis:alpine
    networks:
      - bukal-development

  # Frontend service
  next-app:
    container_name: next-app
    build:
      context: ./front/next-app
      dockerfile: dev.Dockerfile
    environment:
      # ENV_VARIABLE: ${ENV_VARIABLE}
      # NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      # URL pour accéder au backend depuis le container frontend
      NEXT_PUBLIC_API_URL: http://web:80
    env_file:
      - ./front/.env
    volumes:
      - ./front/next-app/src:/app/src
      - ./front/next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - bukal-development
    depends_on:
      - web

networks:
  bukal-development:

volumes:
  postgres-data-development:
